# Generated by Django 5.2 on 2025-05-07 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
        ("order", "0003_order_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="customer.customer",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
